nodeLinker: pnp
packageManager: "yarn@4.0.1"

# os: [
# "linux",
# "darwin",
# "win32",
# ],

# cpu: [
# " x64",
# "ia32",
# "arm64",
# ],


# # Array of folder glob patterns referencing the workspaces of the project.

# # Workspaces are an optional feature used by monorepos to split a large project into semi-independent subprojects, each one listing their own set of dependencies. The workspaces field is a list of glob patterns that match all directories that should become workspaces of your application. Consult the workspaces documentation for more information.

# workspaces: [
#   "packages/*",
# ],
