global:
  scrape_interval: 120s


scrape_configs:
  - job_name: 'nestjs_app'
    static_configs:
      - targets: ['localhost:3000'] # Adjust this if change the app to run on a different port or host
h
